CREATE DATABASE $(MSSQL_DATABASE);
GO

USE $(MSSQL_DATABASE);
GO

CREATE LOGIN $(MSSQL_USER) WITH PASSWORD = '$(MSSQL_PASSWORD)';
CREATE USER $(MSSQL_USER) FOR LOGIN $(MSSQL_USER); 
GO

ALTER ROLE db_owner ADD MEMBER $(MSSQL_USER);
GO
